-- DATA PROFILING
/*All countries our customers come from*/
SELECT DISTINCT
    CNTRY
FROM
    erp_loc_sylver;
    
/*Youngest and oldest cusomer*/
SELECT 
    MAX(BDATE) AS youngest,
    TIMESTAMPDIFF(YEAR, MAX(BDATE), CURRENT_DATE()) AS youngest_age,
    MIN(BDATE) AS oldest,
    TIMESTAMPDIFF(YEAR, MIN(BDATE), CURRENT_DATE()) AS oldest_age
FROM
    erp_cust_sylver;
    
/*Explore all product categories*/
SELECT DISTINCT
    c.CAT AS category,
    c.SUBCAT AS subcategory,
    p.prd_nm AS product_name
FROM
    erp_px_cat_sylver c
        LEFT JOIN
    crm_product_sylver p ON c.id = p.cat_id;
    
/*Date of the first and last order*/
/*How many years of sales are available*/
SELECT 
    MAX(sls_order_dt) AS last_order_date,
    MIN(sls_order_dt) AS first_order_date,
    ABS(FLOOR(DATEDIFF(MIN(sls_order_dt), MAX(sls_order_dt)) / 365)) AS years_sales,
    ABS(CEIL(DATEDIFF(MIN(sls_order_dt), MAX(sls_order_dt)) / 30)) AS month_sales
FROM
    crm_sales_sylver;
    
-- MEASURE EXPLORATION
/*Total sales*/
/*Total items sold*/
/*Average selling price*/
/*Total number of orders*/
/*Total number of customers that has place an order*/
SELECT 
    SUM(sls_sales) AS total_sales,
    SUM(sls_quantity) AS items_sold,
    FLOOR(AVG(sls_price)) AS avg_price,
    COUNT(DISTINCT sls_ord_num) AS tot_orders,
    COUNT( DISTINCT sls_cust_id) AS tot_cust_order
FROM
    crm_sales_sylver;
/*Total number of products*/
SELECT 
    COUNT(DISTINCT prd_key) AS tot_products
FROM
    crm_product_sylver;
/*Total number of customers*/  
SELECT 
    COUNT(cst_id) AS tot_customers
FROM
    crm_customer_sylver;
    
-- Report that shows all key metrics of the business    
SELECT 
    'Total Sales' AS measure_name, SUM(sls_sales) AS measure_value
FROM
    crm_sales_sylver
UNION ALL
SELECT 
    'Total Quantity' AS measure_name, SUM(sls_quantity) AS measure_value
FROM
    crm_sales_sylver
UNION ALL
SELECT 
    'Average Price' AS measure_name, FLOOR(AVG(sls_price)) AS measure_value
FROM
    crm_sales_sylver
UNION ALL
SELECT 
    'Total Nr. Orders' AS measure_name, COUNT(DISTINCT sls_ord_num) AS measure_value
FROM
    crm_sales_sylver
UNION ALL
SELECT 
    'Total Nr. Products' AS measure_name, COUNT(DISTINCT prd_key) AS measure_value
FROM
    crm_product_sylver
UNION ALL
SELECT 
    'Total Nr. Customers' AS measure_name, COUNT(cst_id) AS measure_value -- No need to include the number of the customers that have placed an order because is the same of the number of customers
FROM
    crm_customer_sylver;
    
-- MEASURE VALUES BY CATEGORIES
/*Total customers by country*/
SELECT 
    CNTRY, COUNT(CID) AS tot_cust_country
FROM
    erp_loc_sylver
GROUP BY CNTRY;
/*Total customers by gender*/
SELECT 
    GEN, COUNT(CID) AS tot_cust_gender
FROM
    erp_cust_sylver
GROUP BY GEN;
/*Total products by category*/
/*Average costs in each category*/
SELECT 
    p.CAT,
    COUNT(c.cat_id) AS tot_products_cat,
    FLOOR(AVG(c.prd_cost)) AS avg_cost_products
FROM
    erp_px_cat_sylver P
        LEFT JOIN
    crm_product_sylver c ON p.ID = c.cat_id
GROUP BY p.CAT;
/*Total revenue generated for each category*/
SELECT 
    p.CAT AS category, SUM(s.sls_sales) AS revenue
FROM
    crm_sales_sylver s
        INNER JOIN
    (SELECT 
        prd_key, MAX(cat_id) AS cat_id
    FROM
        crm_product_sylver
    GROUP BY prd_key) c ON s.sls_prd_key = c.prd_key
        INNER JOIN
    erp_px_cat_sylver p ON c.cat_id = p.ID
GROUP BY p.CAT;
/* The category components does not appear, is an error or there are no sales for this category*/
SELECT SUM(s.sls_sales) AS sales_components
FROM crm_sales_sylver s
JOIN crm_product_sylver c 
    ON s.sls_prd_key = c.prd_key
JOIN erp_px_cat_sylver p 
    ON c.cat_id = p.ID
WHERE p.CAT = 'Components'; /*no sales*/
/*Total revenue generated by each costumer*/
SELECT 
    c.cst_id,
    c.cst_fullname,
    SUM(s.sls_sales) AS revenue_by_customers
FROM
    crm_customer_sylver c
        LEFT JOIN
    crm_sales_sylver s ON c.cst_id = s.sls_cust_id
GROUP BY c.cst_id
ORDER BY revenue_by_customers DESC;
/*Distribution of sold items across countries*/
SELECT 
    e.CNTRY, SUM(s.sls_quantity) AS distribution_country
FROM
    erp_loc_sylver e
        LEFT JOIN
    crm_customer_sylver c ON e.CID = c.cst_key
        LEFT JOIN
    crm_sales_sylver s ON c.cst_id = s.sls_cust_id
GROUP BY e.CNTRY;

-- RANKING
/*Top 5 highest revenue per product*/
SELECT 
    p.prd_nm, SUM(s.sls_sales) AS tot_revenue
FROM
    crm_sales_sylver s
        LEFT JOIN
    (SELECT 
        prd_key, prd_nm, MAX(cat_id)
    FROM
        crm_product_sylver
    GROUP BY prd_key , prd_nm) p ON s.sls_prd_key = p.prd_key
GROUP BY p.prd_nm
ORDER BY tot_revenue DESC
LIMIT 5;
/*Top 5 lowest revenue per product*/
SELECT 
    p.prd_nm, SUM(s.sls_sales) AS tot_revenue
FROM
    crm_sales_sylver s
        LEFT JOIN
    (SELECT 
        prd_key, prd_nm, MAX(cat_id)
    FROM
        crm_product_sylver
    GROUP BY prd_key , prd_nm) p ON s.sls_prd_key = p.prd_key
GROUP BY p.prd_nm
ORDER BY tot_revenue ASC
LIMIT 5;
/*Top 5 highest revenue per category*/
SELECT 
    c.SUBCAT, SUM(s.sls_sales) AS tot_revenue
FROM
    crm_sales_sylver s
        LEFT JOIN
    (SELECT 
        prd_key, MAX(cat_id) AS cat_id
    FROM
        crm_product_sylver
    GROUP BY prd_key) p ON s.sls_prd_key = p.prd_key
        INNER JOIN
    erp_px_cat_sylver c ON p.cat_id = c.ID
GROUP BY c.SUBCAT
ORDER BY tot_revenue DESC
LIMIT 5;
/*Top 5 lowest revenue per category*/
SELECT 
    c.SUBCAT, SUM(s.sls_sales) AS tot_revenue
FROM
    crm_sales_sylver s
        LEFT JOIN
    (SELECT 
        prd_key, MAX(cat_id) AS cat_id
    FROM
        crm_product_sylver
    GROUP BY prd_key) p ON s.sls_prd_key = p.prd_key
        INNER JOIN
    erp_px_cat_sylver c ON p.cat_id = c.ID
GROUP BY c.SUBCAT
ORDER BY tot_revenue ASC
LIMIT 5;
/*Top 5 selling products*/
SELECT*
FROM(
SELECT p.prd_nm,
DENSE_RANK() OVER (ORDER BY SUM(s.sls_sales) DESC) AS rank_top
FROM crm_sales_sylver s
LEFT JOIN (SELECT 
    prd_key, prd_nm, MAX(cat_id)
FROM
    crm_product_sylver
GROUP BY prd_key , prd_nm) p ON s.sls_prd_key = p.prd_key
    GROUP BY p.prd_nm
    )t
    WHERE rank_top <= 5;
/*Top 5 slow moving products*/
SELECT*
FROM(
SELECT p.prd_nm,
DENSE_RANK() OVER (ORDER BY SUM(s.sls_sales) ASC) AS rank_top
FROM crm_sales_sylver s
LEFT JOIN (SELECT 
    prd_key, prd_nm, MAX(cat_id)
FROM
    crm_product_sylver
GROUP BY prd_key , prd_nm) p ON s.sls_prd_key = p.prd_key
    GROUP BY p.prd_nm
    )t
    WHERE rank_top <= 5;
/*Top 5 selling categories*/
SELECT*
FROM(
SELECT c.SUBCAT,
DENSE_RANK() OVER (ORDER BY SUM(s.sls_sales) DESC) AS rank_top
FROM crm_sales_sylver s
LEFT JOIN (SELECT 
    prd_key, MAX(cat_id) AS cat_id
FROM
    crm_product_sylver
GROUP BY prd_key) p ON s.sls_prd_key = p.prd_key
        INNER JOIN
    erp_px_cat_sylver c ON p.cat_id = c.ID
GROUP BY c.SUBCAT
    )t
    WHERE rank_top <= 5;
/*Top 5 slow moving categories*/
SELECT*
FROM(
SELECT c.SUBCAT,
DENSE_RANK() OVER (ORDER BY SUM(s.sls_sales) ASC) AS rank_top
FROM crm_sales_sylver s
LEFT JOIN (SELECT 
    prd_key, MAX(cat_id) AS cat_id
FROM
    crm_product_sylver
GROUP BY prd_key) p ON s.sls_prd_key = p.prd_key
        INNER JOIN
    erp_px_cat_sylver c ON p.cat_id = c.ID
GROUP BY c.SUBCAT
    )t
    WHERE rank_top <= 5;
/*Top 10 customers*/
SELECT 
c.cst_fullname,
SUM(s.sls_sales) AS revenue,
DENSE_RANK() OVER (ORDER BY SUM(s.sls_sales) DESC) as top_10_customers
FROM crm_customer_sylver c
LEFT JOIN crm_sales_sylver s
ON c.cst_id= s.sls_cust_id
GROUP BY c.cst_fullname
LIMIT 10;
/*Top 10 minor customers*/
SELECT 
c.cst_fullname,
SUM(s.sls_sales) AS revenue,
DENSE_RANK() OVER (ORDER BY SUM(s.sls_sales) ASC) as top_10_customers
FROM crm_customer_sylver c
LEFT JOIN crm_sales_sylver s
ON c.cst_id= s.sls_cust_id
GROUP BY c.cst_fullname
LIMIT 10;
/*Top 5 customers with most orders placed*/
SELECT 
c.cst_fullname,
COUNT(s.sls_ord_num) AS order_nm,
DENSE_RANK() OVER (ORDER BY COUNT(s.sls_ord_num) DESC) as top_5_customers
FROM crm_customer_sylver c
LEFT JOIN crm_sales_sylver s
ON c.cst_id= s.sls_cust_id
GROUP BY c.cst_fullname
LIMIT 5;
/*Top 5 customers with fewest orders placed*/
SELECT 
c.cst_fullname,
COUNT(s.sls_ord_num) AS order_nm,
DENSE_RANK() OVER (ORDER BY COUNT(s.sls_ord_num) ASC) as top_5_customers
FROM crm_customer_sylver c
LEFT JOIN crm_sales_sylver s
ON c.cst_id= s.sls_cust_id
GROUP BY c.cst_fullname
LIMIT 5;